### ISSUE TITLE
Require choosing authentication method upon wallet creation

### ISSUE THREAD

**Issue by powerkangaroo** [zecwalletco/zecwallet-mobile#28] opened 2020-09-14 23:07 UTC
When the wallet is generated or imported, require the user to choose one out of these authentication options:

* Password (specific to this app)
* PIN (specific to this app)
* fingerprint
* Default device screen lock protection (PIN, password, pattern, fingerprint, face lock - whichever is enabled)

Once implemented, for users that upgrade from an older version, require them to make this choice when first opening the wallet.

**Comment by adityapk00** [comment] 2020-12-02 22:37
Duplicate of #17

**Closed by adityapk00** 2020-12-02 22:37 UTC
